# for external service access, see https://console.bluemix.net/docs/containers/cs_apps.html#cs_apps_public_nodeport
apiVersion: v1
kind: Service
metadata:
  name: isamconfig-np
spec:
  type: NodePort
  ports:
    - port: 9443
      name: isamconfig
      protocol: TCP
      nodePort: 30442
  selector:
    app: isamconfig
